language: node_js
cache:
  directories:
  - node_modules
script: node dblp-cite.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master
env:
  matrix:
    secure: iFbpXhc2hHbasP4RzxYWVcNgXHhTwZYOG3KO71Swlo+wiRmZBVMm1Z9p6dDfeXVIbH/OkH3/iZInyKhWweUkI81naukFu0XScahLkB7PyNI1RRmACEd1BdNZqvyvbjzZxvK0OzJbeOIx4DYAljFEFFQb6YAa/LgqTZn5IafgFOEBNnJoYzCEMDSmav2q9B3m7OdYKdCDCxGujX/QrPsaaBH94qyYmMma/wHUFdiyn7lEFYSf/JQV49wQos5nuOTEL2ssf3cPneLVf5D9jvNABmE+cqg2i82EJGZJp6uIQOrzEMXYRKdBAo7zlUCb++6fY/k/7i2ASqMkEpwFckGDkZAKSFHcUhfEukKa2Nf31HwbN9ZzFaKMJZ23+ErkJP54JGPlWf5ziWU1wmyt7UXK+CRLV5PDjG/Rh2X93AKu0BDRom6gtXtAxnPLVLBfklROUH4YK9q5BJ2foXDACZxLWRIO1fbGABHzyFvnyFmSU6j3Ec7WyWBdl8w7P3JMXT6SxTiRRq/pR1W5V3VdK2z/Xygk/JSZnI1SgpMZF3Y25JMRmG6SpFt7u3RtiOEqv+vUQTacjKzgwyjHol5Y8TL05jeDQOupKXLCQsW4XKLpzFzjmtXQNComdDuCxTjaxhClu8CQgXpzMwCgIcEmYJdZQ94Gql2b3dLEiTggQ9m+gCQ=
